#!/usr/bin/env bash

sudo apt install docker.io

# Make Docker start automatically on system boot
sudo systemctl enable --now docker

sudo apt-get -y install docker-compose

# Now add user to the 'docker' group
# sudo usermod -a -G docker $USER
